---
- name: install dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
    update_cache: yes

- name: Add an Apt signing key 
  apt_key:
    url: "{{ key }}"
    state: present

- name: adding repo gitlab (1/2)
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/gitlab_gitlab-ce-archive-keyring.gpg] https://packages.gitlab.com/gitlab/gitlab-ce/debian/ bullseye main
    state: present

- name: adding repo gitlab (2/2)
  apt_repository:
    repo: deb-src [signed-by=/usr/share/keyrings/gitlab_gitlab-ce-archive-keyring.gpg] https://packages.gitlab.com/gitlab/gitlab-ce/debian/ bullseye main
    state: present

- name: install gitlab-ce
  apt:
    name: gitlab-ce
    state: present
    update_cache: yes
  environment:
    EXTERNAL_URL: "{{ external_url }}"