---
- name: verify if helm is present
  file:
    state: file
    path: /usr/local/bin/helm
  ignore_errors: true
  register: helm

- name: unarchive helm for install
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{helm_version}}-{{os_type}}-{{architecture_type}}.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: archive
  when: helm.failed == true

- name: unarchive helm for upgrade
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{helm_version}}-{{os_type}}-{{architecture_type}}.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: archive2
  when: upgrade == true

- name: set helm to /usr/local/bin/helm
  copy:
    src: "/tmp/{{ os_type }}-{{ architecture_type }}/helm"
    dest: /usr/local/bin/helm
    mode: u+rx,g-rx,o-rwx
  when: archive.changed or archive2.changed

- name: remove installation archive
  file:
    state: absent
    path: "/tmp/{{ os_type }}-{{ architecture_type }}"
  when: archive.changed or archive2.changed