---
#Prerequis "ansible-galaxy collection install community.docker"
#ansible-galaxy collection install kubernetes.core

- name: Install Rancher manager on Debian 11
  hosts: all
  become: yes
  roles:
    - docker
  vars:
    rancher_version: v2.7.1-head
    stockage_rancher: /opt/rancher 
  tasks:
  - name: lancement du conteneur rancher
    register: rancher
    community.docker.docker_container:
      name: rancher
      image: "rancher/rancher:{{ rancher_version }}"
      state: started
      privileged: true
      restart_policy: "unless-stopped"
      published_ports:
      - 80:80
      - 443:443
      volumes:
      - "{{ stockage_rancher }}:/var/lib/rancher"

  - name: "Id du conteneur {{ rancher.container.Config.Hostname }}"
    changed_when: false
    debug: 
      msg: "Pour récupérer le mot de passe par défaut: sudo docker logs {{ rancher.container.Config.Hostname }} 2>&1 | grep 'Bootstrap Password:'"