---
hostname: superrancher.io
replicas: 1
#penser à passer le mot de passe en secret ansible
bootstrapPassword: Aqwzsxedc@01
persistance:
  enabled: true

#ingress:
#  tls:
#    source: secret
#If private SSL certificate 
privateCA: false

#If you have private registries, catalogs or a proxy that intercepts certificates
additionalTrustedCAs: false