---
#regarder les variables de sortie pour gérer son idempotence
- name: installation de la collection kubernetes.core
  command: "ansible-galaxy collection install kubernetes.core"
  register: collection_output
  changed_when: false 

- name: Add Helm repository
  apt_repository:
    repo: "deb https://helm.sh/helm/{{ helm_version }}/debian stable main"
    state: present
  vars:
    helm_version: 3.4.1

- name: Install GPG Key
  apt_key:
    url: https://helm.sh/helm/{{ helm_version }}/gpg/D88E42B4
    state: present

- name: Install Helm
  apt:
    name: helm
    state: present

- name: install pip packages
  pip: 
    name: "{{ item }}"
  loop:
    - python3-pip
    - PyYAML
    - kubernetes>=12.0.0	
    - jsonpatch

  