# from https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
deployment:
  kind: DaemonSet

globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"
  - "--serversTransport.insecureSkipVerify=true"

ports:
  web:
    port: 80
    hostPort: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    hostPort: 443
    expose: true
    exposedPort: 443
tolerations:
  # this toleration is to have the daemonset runnable on master nodes
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
