---
type_of_install: package
external_url: "https://super-gitlab.com"

private_cert:
  use_private_cert: no
  key_path: /your_path_to_key
  crt_path: /your_path_to_crt 

dependencies:
- curl 
- openssh-server 
- ca-certificates 
- perl
- postfix
- gnupg
- debian-archive-keyring
- apt-transport-https

key: "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey"
deb_rep: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/config_file.list?os=debian&dist=11&source=script