---
- name: install rancher
  import_tasks: "{{ role_path }}/tasks/install_rancher.yaml"
  tags: install_rancher

- name: upgrade rancher
  import_tasks: "{{ role_path }}/tasks/upgrade_rancher.yaml"
  tags: ["upgrade_rancher", "never"]

- name: uninstall rancher
  import_tasks: "{{ role_path }}/tasks/uninstall_rancher.yaml"
  tags: ["uninstall_rancher", "never"]